### PR TITLE
Add Open Collective widget to homepage

### PR DESCRIPTION
**Pull request by cece-playco**
- Add widget to homepage above ClosingSection
Screen Shot 2023-03-17 at 1 50 00 PM

### CODE REVIEW

**Comment by Zyie** [comment]
I've noticed a couple of issues with this while testing

image

- In dark mode the "15 organizations are supporting PixiJS - The HTML5 Creation Engine." is not readable
- This doesn't work with mobile layout

image
- Can we make this much narrower. It spanning the full page doesn't look good when everything else is is fairly compact

**Comment by cece-playco** [comment]
@Zyie Just wanted to get some clarification on the mobile layout, is the issue that there's only 1 item per row or are there other bugs?

**Comment by Zyie** [comment]
> @Zyie Just wanted to get some clarification on the mobile layout, is the issue that there's only 1 item per row or are there other bugs?

The main mobile issue is that the sponsors get cut off and there is no way to scroll to see them all

image


Also it would be nice to see if we can change the background image used in the cards to be pink?
So if you could investigate this a little that would be great!

**Comment by cece-playco** [comment]
@Zyie Got it, I think that's an issue that happens if you're resizing the window to be smaller, I didn't notice it when I was opening the page on mobile first- it looks like the ability to customize the widget styling is limited since most of it is set in the script, so I'm reaching out to Open Collective to see if there are workarounds!

**Comment by Zyie** [comment]
closing in favour of #37

**Pull request closed without merging**
