### PR TITLE
Homepage animations

### PR DESCRIPTION
**Pull request by thalys**

### CODE REVIEW

**Comment by Zyie** [comment]
Couple of things i noticed

- the animations are not using the same ease, the new site feels much slower. We should try an match the old site a bit more

- When the devices animate in they are not masked so it looks strange that they appear over the top of the section below
image

**Comment by Zyie** [comment]
Couple more issues

- The animations for the features section is still too slow

- This section is missing the animations from the main site
image

**Comment by thalys** [comment]
@Zyie Added the animation to the bottom of the page and fixed a bit easing and speed of other animation

**Review by Zyie — APPROVED** [review]
This looks great, good work!

**Pull request merged**
